apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: davids-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: ghcr.io/expruc/kubernetes-gradutaion-drill/k8s-final-drill:backend
        ports:
        - containerPort: 8080

apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: davids-namespace
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
  