apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: davids-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: ghcr.io/expruc/kubernetes-gradutaion-drill/k8s-final-drill:frontend
        ports:
        - containerPort: 5050

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: davids-namespace
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
  type: ClusterIP