# frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: davids-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: ghcr.io/expruc/kubernetes-gradutaion-drill/k8s-final-drill:frontend
        ports:
        - containerPort: 5050
        env:
        - name: PORT
          value: "5050"
        - name: BACKENDURL
          value: "http://backend-service:8080"  

