# Generated by Django 4.2.7 on 2023-11-06 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('open_date', models.DateTimeField(auto_now=True)),
                ('close_date', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=30)),
                ('can_draft', models.BooleanField(default=False)),
                ('can_archive', models.BooleanField(default=False)),
                ('connected_users', models.ManyToManyField(related_name='connected_users', to='users.user')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='EventFile',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event')),
                ('file', models.FileField(upload_to='files/')),
            ],
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='EventChat',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event')),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chats.chat')),
            ],
            bases=('events.event',),
        ),
    ]
