# Generated by Django 4.2.7 on 2023-11-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unread_messages',
            field=models.ManyToManyField(default=[], related_name='user', to='chats.message'),
        ),
    ]
