# Generated by Django 4.2.7 on 2023-11-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        ('users', '0004_remove_user_id_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unread_messages',
            field=models.ManyToManyField(default=[], related_name='User', to='chats.message'),
        ),
    ]
