# Generated by Django 4.2.7 on 2023-11-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        ('users', '0008_user_unread_messages_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unread_messages',
            field=models.ManyToManyField(blank=True, related_name='users', to='chats.message'),
        ),
    ]
