# Generated by Django 4.2.6 on 2023-10-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('attack_priority', models.PositiveIntegerField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('enemy_organization', models.CharField(max_length=100)),
                ('target_goal', models.CharField(max_length=100)),
                ('was_target_damaged', models.BooleanField()),
                ('target_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
