# Generated by Django 4.2.4 on 2023-10-17 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.person')),
                ('work_place', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=6)),
                ('children', models.ManyToManyField(related_name='Children', to='people.person')),
            ],
            bases=('people.person',),
        ),
    ]
