# Generated by Django 4.2.4 on 2023-10-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_alter_parent_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='children',
            field=models.ManyToManyField(default=[], related_name='Children', to='people.person'),
        ),
    ]
