# Generated by Django 4.2.4 on 2023-10-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_alter_parent_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='children',
            field=models.ManyToManyField(default=[], related_name='parents', to='people.person'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
