# Generated by Django 4.2.6 on 2023-10-19 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_alter_parent_children_alter_parent_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='birth_date',
            new_name='birthDate',
        ),
    ]
