# Generated by Django 4.2.6 on 2023-10-19 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_rename_birth_date_person_birthdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='city',
            new_name='homeTown',
        ),
    ]
