# Generated by Django 4.2.6 on 2023-10-19 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_rename_city_person_hometown'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='salary',
            new_name='baseSalary',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='work_place',
            new_name='work',
        ),
    ]
