# Generated by Django 4.2.6 on 2023-10-19 13:16

from django.db import migrations, models
from django.db.models import F
from django.db.models.functions import Ceil


def round_salaries(apps, schema_editor):
    parent_obj = apps.get_model('people', 'Parent')
    parent_obj.objects.update(baseSalary=Ceil(F('baseSalary')))


class Migration(migrations.Migration):
    dependencies = [
        ('people', '0009_rename_salary_parent_basesalary_and_more'),
    ]

    operations = [
        migrations.RunPython(round_salaries, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='parent',
            name='baseSalary',
            field=models.PositiveIntegerField(default=0, max_length=6),
        ),
    ]
