# Generated by Django 4.2.6 on 2023-10-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_alter_parent_basesalary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='baseSalary',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
