# Generated by Django 4.2.6 on 2023-10-19 14:11

import django.core.validators
from django.db import migrations, models
from django.db.models import F
from django.db.models.functions import Ceil


def round_salaries(apps, schema_editor):
    parent_obj = apps.get_model('people', 'Parent')
    parent_obj.objects.update(baseSalary=Ceil(F('baseSalary')))


class Migration(migrations.Migration):
    dependencies = [
        ('people', '0014_alter_parent_basesalary'),
    ]

    operations = [
        migrations.RunPython(round_salaries, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='parent',
            name='baseSalary',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
